services:
  nginx:
    image: nginx:${NGINX_IMAGE_VERSION}
    restart: always
    volumes:
      - ./storage/php/wordpress:/var/www/html
      - ./config/nginx/cert:/etc/nginx/cert
      - ./config/nginx/conf/${WORDPRESS_NGINX_CONF}.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
  mysql:
    image: mysql:${MYSQL_IMAGE_VERSION}
    platform: linux/x86_64
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
  wordpress:
    image: wordpress:${WORDPRESS_IMAGE_VERSION}
    restart: always
    volumes:
      - ./storage/php/wordpress:/var/www/html
      - ./config/php/etc/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
